<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Artist', 'doctrine');

/**
 * BaseArtist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Album
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getAlbum() Returns the current record's "Album" collection
 * @method Artist              setId()    Sets the current record's "id" value
 * @method Artist              setName()  Sets the current record's "name" value
 * @method Artist              setAlbum() Sets the current record's "Album" collection
 * 
 * @package    aguayo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Album', array(
             'local' => 'id',
             'foreign' => 'artist_id'));
    }
}