<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StockHystory', 'doctrine');

/**
 * BaseStockHystory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $album_id
 * @property string $description
 * @property integer $alue
 * @property Album $Album
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getAlbumId()     Returns the current record's "album_id" value
 * @method string       getDescription() Returns the current record's "description" value
 * @method integer      getAlue()        Returns the current record's "alue" value
 * @method Album        getAlbum()       Returns the current record's "Album" value
 * @method StockHystory setId()          Sets the current record's "id" value
 * @method StockHystory setAlbumId()     Sets the current record's "album_id" value
 * @method StockHystory setDescription() Sets the current record's "description" value
 * @method StockHystory setAlue()        Sets the current record's "alue" value
 * @method StockHystory setAlbum()       Sets the current record's "Album" value
 * 
 * @package    aguayo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStockHystory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stock_hystory');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('album_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 225, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 225,
             ));
        $this->hasColumn('alue', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Album', array(
             'local' => 'album_id',
             'foreign' => 'id'));
    }
}