<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('YearProduction', 'doctrine');

/**
 * BaseYearProduction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $date
 * @property Doctrine_Collection $Album
 * 
 * @method integer             getId()    Returns the current record's "id" value
 * @method integer             getDate()  Returns the current record's "date" value
 * @method Doctrine_Collection getAlbum() Returns the current record's "Album" collection
 * @method YearProduction      setId()    Sets the current record's "id" value
 * @method YearProduction      setDate()  Sets the current record's "date" value
 * @method YearProduction      setAlbum() Sets the current record's "Album" collection
 * 
 * @package    aguayo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseYearProduction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('year_production');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Album', array(
             'local' => 'id',
             'foreign' => 'year_production_id'));
    }
}