<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/12/06 21:04:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=aguayo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
