<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/12/07 01:03:00
$this->security = array (
  '@homepage' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
