<?php

/**
 * StockHystoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StockHystoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StockHystoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StockHystory');
    }
}