<?php

/**
 * YearProductionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YearProductionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YearProductionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('YearProduction');
    }
}