<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/12/06 22:48:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=aguayo_db',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
