<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/12/07 00:46:13
sfConfig::add(array(
  'mod_yearproduction_enabled' => true,
  'mod_yearproduction_view_class' => 'sfPHP',
));
